

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nestjs-quickreels/logs:/src/logs
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk

  quickreels-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./nestjs-quickreels/logs:/src/logs
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local

networks:
  elk:
    driver: bridge
