name: Quickreels Workflow

on:
  push:
    branches:
      - emp
  pull_request:
    branches:
      - emp

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

  update-checkov:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3
        with:
          fetch-depth: '0'

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Run Super Linter
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: emp
          VALIDATE_ALL_CODEBASE: 'false'
          VALIDATE_JSCPD: 'false'
          VALIDATE_YAML: 'false'
          VALIDATE_JAVASCRIPT_ES: 'false'
          VALIDATE_TYPESCRIPT_STANDARD: 'false'
          VALIDATE_TYPESCRIPT_ES: 'false'
          JSCPD_CONFIG_FILE: .jscpd.json
          LOG_LEVEL: DEBUG

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@94be32d33f46ce5f2f07200bb5df4f5036b7296c

      - name: update-checkov-version
        id: checkov_version
        run: |
          version=$(curl -s https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0].name')
          sed -i'.bkp' -e 's/docker:\/\/ghcr.io\/bridgecrewio\/checkov.*'\''/docker:\/\/ghcr.io\/bridgecrewio\/checkov:'"${version}"''\''/g' action.yml
          rm action.yml.bkp
          echo "version=$version" >> $GITHUB_OUTPUT