name: Quickreels workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Ensure this matches your project's Node.js version requirement

      - name: Run Super Linter
        uses: super-linter/super-linter@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: development
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML_PRETTIER: false
